### ISSUE TITLE
What is the difference between 'collectionName' and 'collection' configuration parameters?

### ISSUE THREAD

**Issue by oshihirii** [2do2go/rate-limit-mongo#19]
Hello,

I am referring to:

https://github.com/2do2go/rate-limit-mongo#configuration

I am confused as to why there are two parameters that seem to refer to the same thing?

> collectionName: string -- name of collection for storing records. Defaults to expressRateRecords

> collection: object -- mongodb collection instance. Required if uri hasn't been set.

Sorry if I am not understanding this correctly.  

Thank You.

**Comment by okv** [comment]
Hello.
`collection` option accepts already connected [mongodb native collection instance](http://mongodb.github.io/node-mongodb-native/3.3/api/Collection.html). On the other hand `collectionName` is supposed to be used with `uri` and other options (like `user`, `password`, etc) to create collection instance. So it's kind of different ways to provide collection instance for the lib.
