### ISSUE TITLE
Connection string format

### ISSUE THREAD

**Issue by oshihirii** [2do2go/rate-limit-mongo#20]
Hello,

Before trying to implement `rate-limit-mongo`, to successfully connect to MongoDB I use a connection string in these formats:  

**Local** - there is _no username, password or database defined_:  
  
```js
connection_string = mongodb://localhost:27017"
```
**Production Server (MongoDB Atlas)**  
The related `env` property value is defined like this - _a username, password and database is defined_:
```js
connection_string = "mongodb+srv://<user-name>:<user-password>@cluster0.vewnz.azure.mongodb.net/Cluster0?retryWrites=true&w=majority&useNewUrlParser=true&useUnifiedTopology=true"
```
Note that `Cluster0` (with a capital 'C') is the database name defined.  

The connection is made with this code:
```js
const MongoClient = require('mongodb').MongoClient;  

MongoClient.connect(connection_string, function(err, client) {
    if (err) {
        throw err;
    } else {
        mongo_client = client;
        console.log("made a connection to server");
    }
});
```
And when I want to make requests to a database, I use something like this (_database and collection is defined_):  
```js
var collection = mongo_client.db("some-database-name").collection("some-collection-name");
```
However, now I am trying to implement `rate-limit-mongo`.

I can see that the [default configuration options](https://github.com/2do2go/rate-limit-mongo#configuration) for `MongoStore` are:

```js
store: new MongoStore({
  uri: "mongodb://127.0.0.1:27017/test_db",
  collectionName: "expressRateRecords",
  user: "",
  password: "",
  authSource: "",
  collection: "",
  expireTimeMs: 60 * 1000,
  resetExpireDateOnChange: false,
  errorHandler: "_.noop",
  createTtlIndex: true
});
```
I am wondering whether I can define `MongoStore` with these parameters _only_:
```js
uri: connection_string,
collectionName: "expressRateRecords"
```
Because the `user` and `password` are already defined in my connection string (in production environment) and locally they are not required?   

Thank You.  

**Edit:**  

The suggestion above works in local environment with the connection string `mongodb://localhost:27017`, but not in production environment with MongoDB Atlas and the connection string:

```js
mongodb+srv://<user-name>:<user-password>@cluster0.vewnz.azure.mongodb.net/Cluster0?retryWrites=true&w=majority&useNewUrlParser=true&useUnifiedTopology=true
```   
There is no error message displayed on the server, but the entry is not added to the `expressRateRecords` (database) > `expressRateRecords` (collection).  

It also looks like it has created a database called `Cluster0` containing a collection called `expressRateRecords`.  

And I had already created a database called `expressRateRecords` containing a collection called `expressRateRecords`.  

Entries are not going into either database or collection.  

**Edit 2:**

I have also tried the following:
```js
var apiLimiter = rateLimit({
    windowMs: 5 * 60 * 1000, // 5 minutes
    max: 3,
    headers: false,
    handler: function(req, res) {
        res.status("429");
    },
    store: new MongoStore({
        uri: process.env.RATE_LIMIT_MONGO_CONFIG_CONNECTION_STRING,
        collectionName: "expressRateRecords",
        user: process.env.RATE_LIMIT_MONGO_CONFIG_USER,
        password: process.env.RATE_LIMIT_MONGO_CONFIG_PASSWORD
    })
});
```  
When the connection string is:
```js
mongodb+srv://cluster0.vewnz.azure.mongodb.net/expressRateRecords?retryWrites=true&w=majority&useNewUrlParser=true&useUnifiedTopology=true
```
I get 500 error:
```
MongoError: Database name expressRateRecords?retryWrites=true&amp;w=majority&amp;useNewUrlParser=true&amp;useUnifiedTopology=true is too long. &nbsp;Max database name length is 38 bytes.
```
When the connection string is:
```js
mongodb+srv://cluster0.vewnz.azure.mongodb.net/expressRateRecords
```
I get 500 error:
```
"MongoError: Authentication failed"
```
When the connection string is:
```js
mongodb+srv://user-name:password@cluster0.vewnz.azure.mongodb.net/expressRateRecords
```
I get 500 error:
```
"MongoError: Authentication failed"
```

**Comment by oshihirii** [comment]
This worked for me in the end:

```js
var apiLimiter = rateLimit({
    windowMs: 5 * 60 * 1000, // 5 minutes
    max: 3,
    headers: false,
    handler: function(req, res) {
        res.status("429").end();
    },
    store: new MongoStore({
        uri: process.env.RATE_LIMIT_MONGO_CONFIG_CONNECTION_STRING,
        collectionName: "expressRateRecords"
    })
});
```
where connection string is:
```js
mongodb+srv://user-name:password@cluster0.vewnz.azure.mongodb.net/expressRateRecords
```
So basically, `username`, `password` and `database` defined in the `connection string` and only using the `uri` and `collectionName` config parameters.

**Comment by oshihirii** [comment]
The only weird thing that is happening now is I am getting 524 errors after exceeding rate, in Chrome dev tools, and that status is not handled by my application so there is no user feedback.  Not sure why a 524 is being returned when i specifically define `res.status("429");`.

**Comment by okv** [comment]
Hello.
There a lot of questions in this issue and I don't get them all ;)
I hope my [answer](https://github.com/2do2go/rate-limit-mongo/issues/19#issuecomment-690970868) about `collection` and `collectionName` options will be helpful - it describes how to provide connected instance of the collection.
I'm closing the issue, but if you have specific questions feel free to post.

**Comment by okv** [comment]
I'm not aware of that possible issue with Cloudflare and 429, 524 http statuses, sorry cannot help with that.

**Comment by oshihirii** [comment]
@okv - it ended up being a problem with my code, so I deleted the comment related to the 524 error.  

For reference, I was using:

```js
    handler: function(req, res) {
        res.status("429");
    },
``` 
And I don't think the request was 'terminating' and cloudflare was returning a 524 error.

So I used the following code and it resolved the issue:  
```js
    handler: function(req, res) {
        res.status("429").end(); // <--- just added .end()  
    },
```

**Comment by Hemann55** [comment]
> This worked for me in the end:
> 
> ```js
> var apiLimiter = rateLimit({
>     windowMs: 5 * 60 * 1000, // 5 minutes
>     max: 3,
>     headers: false,
>     handler: function(req, res) {
>         res.status("429").end();
>     },
>     store: new MongoStore({
>         uri: process.env.RATE_LIMIT_MONGO_CONFIG_CONNECTION_STRING,
>         collectionName: "expressRateRecords"
>     })
> });
> ```
> 
> where connection string is:
> 
> ```js
> mongodb+srv://user-name:password@cluster0.vewnz.azure.mongodb.net/expressRateRecords
> ```
> 
> So basically, `username`, `password` and `database` defined in the `connection string` and only using the `uri` and `collectionName` config parameters.

@okv Consider adding a note in the documentation that "If uri includes username and password, then do not included user and password in the config object."
