### ISSUE TITLE
Clarification of expireTimeMs and resetExpireDateOnChange configuration parameters

### ISSUE THREAD

**Issue by oshihirii** [2do2go/rate-limit-mongo#21]
Hello,

Can I just clarify what these configuration parameters mean:

`expireTimeMs` - is this how often the background task is run that removes expired entries?  

`resetExpireDateOnChange` - i don't understand the description:
> indicates whether expireDate should be reseted when changed or not 

I can see that `expirationDate` is a property in a MongoDB entry for a related hit from an IP address.  

But I don't understand what "when changed" means?  

When would an entry "be changed", other than when the `counter` property in the MongoDB entry is incremented after another hit from the same IP address?   

And why would it be helpful for `resetExpireDateOnChange` to be reset every time an IP address makes another request?  Wouldn't that just give them the ability to make unlimited hits if the `expirationDate` keeps being reset on each request?  

Thank You.

**Comment by okv** [comment]
Hello.

> expireTimeMs - is this how often the background task is run that removes expired entries?

Yes, but remember that current implementation uses on mongodb ttl indexes (background task that removes expired documents runs every 60 seconds). So in practice you might not have documents deleted every `expireTimeMs`.

> But I don't understand what "when changed" means?

It means when document in the collection updated - in case of our collection when counter increased of decreased. `resetExpireDateOnChange` determines whether to update document expiry date on counter change or not. This is only about resetting expiry date not the counter value itself. In fact this option set to true prolongs the life of the counter for the ip address and therefore restricts requests from this address for a longer time.

You're welcome, hope this will help.
