### ISSUE TITLE
Use client's real IP address instead of proxy.

### ISSUE THREAD

**Issue by badgersmans** [2do2go/rate-limit-mongo#25]
In my app, this is the code I use to get the client's real ip address, it works even if behind heroku
```
    let ip = req.headers["x-forwarded-for"];
    if (ip){
      var list = ip.split(",");
      ip = list[list.length-1];
    } else {
      ip = req.connection.remoteAddress;
    }
```

But heroku has different IP than what the above code will give you.

Here is an example heroku IP, it's different everytime, so the blocking of IP isn't so effective in this case, as they all have different counter values for the different IPs, I think it would be better if the real client IP was used, this way there is one IP with one counter value, making the blocking of IP more effective.

![image](https://user-images.githubusercontent.com/64647433/97933023-89e50480-1dac-11eb-8b68-21b071c22d86.png)

**Comment by okv** [comment]
If I understand correctly you want to use another key for a counter, please checkout [keyGenerator option](https://github.com/nfriedly/express-rate-limit#keygenerator). Seems like it's what you need.

**Comment by badgersmans** [comment]
yeah amazing! that's exactly what I needed, thank you

**Comment by okv** [comment]
You're welcome, glad that it helped
