### ISSUE TITLE
It is not immediately clear from the documentation that some public methods can take an optional callback

### ISSUE THREAD

**Issue by cakesmith** [2do2go/rate-limit-mongo#31]
The Readme currently states:

"MongoStore class provides public methods (incr, decrement, resetKey) required by express-rate-limit."

It is not immediately clear that these methods can (or should) take an optional callback. 

When using `mongoose` to provide a backing store collection, its `deleteOne()` method requires a callback for proper operation: https://mongoosejs.com/docs/queries.html#executing

 This could easily lead to an improper (synchronous) implementation of `resetKey()`, causing a race condition between `mongo` and `express`.

**Comment by okv** [comment]
Hey there! Sorry for the late reply.

There are just names of methods in this repository's Readme. There is no goal to provide comprehensive documentation for these methods there. If you need more details (e.g. if you want to implement your own store) please take a look at [Express Rate Limit Readme](https://github.com/nfriedly/express-rate-limit#store).

**Comment by okv** [comment]
I'm closing it for now
