### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by harrisonhoward** [2do2go/rate-limit-mongo#35]
`(node:26384) [MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.`

**Comment by lblo** [comment]
Hi,
We have the same issue. Any update on this?

**Comment by ghost** [comment]
Please update the package @okv

**Comment by lblo** [comment]
FYI we have applied the following patch.

![image](https://user-images.githubusercontent.com/47742293/130093278-2ccb01ee-d20d-4183-91a4-772ec7f31dfe.png)

**Comment by okv** [comment]
Hi there!
Sorry for the late reply I will try to take a look at it soon.

**Comment by abhijoshi2k** [comment]
Facing same issue. Any updates?

**Comment by okv** [comment]
A fixed version published to the npm registry as rate-limit-mongo@2.3.2
