### ISSUE TITLE
Cannot read property 'counter' of null

### ISSUE THREAD

**Issue by harvardpan** [2do2go/rate-limit-mongo#39]
After updating to 2.3.2 version of rate-limit-mongo, getting an error whenever the application starts up. The exception stack trace:
```
[TypeError]: Cannot read property 'counter' of null
      at Group.<anonymous> (/fusion/node_modules/rate-limit-mongo/lib/mongoStore.js:158:32)
      at Group.<anonymous> (/fusion/node_modules/twostep/lib/twoStep.js:171:15)
      at next (/fusion/node_modules/twostep/lib/twoStep.js:159:9)
      at Group.done (/fusion/node_modules/twostep/lib/twoStep.js:30:16)
      at Group._fillSlot (/fusion/node_modules/twostep/lib/twoStep.js:52:8)
      at /fusion/node_modules/twostep/lib/twoStep.js:77:9
      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
```

Noticed in 2.3.2, there was a commit (https://github.com/2do2go/rate-limit-mongo/commit/41e917b60ae80de313f4849bfe4dd1f4e9f52b42) that changed the options passed to be `returnDocument` or `returnNewDocument` instead of `returnOriginal`. 

The error occurs whenever the upserts needs to create a new record. It returns an object which doesn't have the `counter` property, which seems to be in line with returning the pre-upsert record rather than the post-upsert record.

**Comment by okv** [comment]
Hi @harvardpan !
Which `mongodb` version do you use? (you can check this out with `npm ls mongodb` command).
rate limit mongo 2.3.2 requires mongodb 3.6.7 or newer which is describe in the package.json as `^3.6.7`.
Most likely it's an issue with `mongodb` package version you can try to remove and install rate limit mongo and mongodb (if you use it directly) packages.

**Comment by harvardpan** [comment]
@okv Thanks so much for pointing me in the right direction. I do see that we're currently using `mongodb` 3.2.7 directly, but that the `rate-limit-mongo` package is pointing to `mongodb@3.7.1` for a dependency. We're already planning to update the MongoDB driver, so will retest again once we update.
