### ISSUE TITLE
windowMs not working

### ISSUE THREAD

**Issue by bj97301** [2do2go/rate-limit-mongo#7]
Seem to just use the 1 minute default no matter what I set for the options.  Tried:
```js
var RateLimit = require('express-rate-limit')
var MongoStore = require('rate-limit-mongo')

var limiter = new RateLimit({
    store: new MongoStore({
        uri: databaseUrl,
        expireTimeMs: 1,
    }),
    skip: shouldSkipRateLimiter,
    windowMs: 1,
    max: 5,
})
app.use(limiter)
```

**Comment by bj97301** [comment]
I think it has to do with this:
```js
self.collection.createIndex({
                    expirationDate: 1
                }, {
                    expireAfterSeconds: 0
                },
                this.slot()
            );
```
Was going to make a pr for this but the tests are not as easy to figure out as I was hoping.  I am going to roll my own store.  Best of luck.

**Comment by okv** [comment]
Hello.

Current implementation uses on mongodb ttl indexes - background task that removes expired documents runs every 60 seconds. As a result, documents may remain in a collection during the period between the expiration of the document and the running of the background task. See [mongodb ttl indexes doc](https://docs.mongodb.com/v3.6/core/index-ttl/#timing-of-the-delete-operation) for more information.
I've just added that note to readme.

So code is ok - works as expected ;)
p.s. Period of running that background task for ttl indexes can be changed, see mongodb docs for details.

**Comment by bj97301** [comment]
I am not so sure of this.  Are you able to change the window to anything besides 60 seconds?

**Comment by okv** [comment]
Sure, but you should also set `expireTimeMs` store option (it overrides `windowMs`).

**Comment by bj97301** [comment]
It does not seem to. Are you able to get it to work?

**Comment by sam13591980** [comment]
I have the same problem. Honestly, you just changed the behavior of the "express-rate-limit" package.

**Comment by okv** [comment]
Sorry but current implementation of ttl indexes in mongodb - background task that removes expired documents, it runs every 60 seconds be default. According to that it's not quite possible to have accurate expiration option.
