### ISSUE TITLE
Add method  `.close()` for disconnecting

### ISSUE THREAD

**Issue by chiawendt** [2do2go/rate-limit-mongo#8]
Thank you for your great work.

 I am having trouble making a test exit because the mongo connection is not closed. It would be nice if mongostore can provide a method for disconnecting. Alternative it could expose the mongoClient so user can disconnect with it.

**Comment by okv** [comment]
Hello, there.

There are some concerns about close method - class instance will not make much sense after closing connection (maybe we should call it destroy); other stores (redis, mem cache) don't have such method (currently all public methods are required by rate limiter), etc. It'll take some time to decide.

Currently as a workaround you can manage mongodb connection manually and pass `collection` option (mongodb collection instance) to the constructor.

Thanks for good words, hope that will help)

**Comment by okv** [comment]
Done in #14
